feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

